os: linux
dist: xenial
language: generic

if: branch IN (master,develop)

before_deploy:
  - npm install -g openode

deploy:
  - provider: script
    script: openode ci-conf $OPENODE_API_KEY shaq-view-test && openode deploy
    on:
      branch: develop
      type: push
  - provider: script
    script: openode ci-conf $OPENODE_API_KEY shaq-view-prod && openode deploy
    on:
      branch: master
      type: push

notifications:
  email:
    - lav@yoctu.com
